### ISSUE TITLE
Gmail is missing icons in ElectronIM

### ISSUE THREAD

**Issue by KirilOkun** [manusa/electronim#115] opened 2022-09-23 10:13 UTC
See attached screenshot.
![Screenshot_20220923_171027](https://user-images.githubusercontent.com/1024870/191939504-eb7512ee-fe97-44e2-88e2-034644de971d.png)

**Comment by KirilOkun** [comment] 2022-09-23 10:15
This is on Kubuntu,  latest Plasma UI.

**Comment by manusa** [comment] 2022-09-23 10:32
Duplicate of https://github.com/manusa/electronim/issues/106

Will be fixed in next release

**Closed by manusa** 2022-09-23 10:32 UTC
