### ISSUE TITLE
Cannot login to services 

### ISSUE THREAD

**Issue by baldimir** [manusa/electronim#14] opened 2020-02-11 13:47 UTC
Hi, I cannot login to a service because the login URLs are being opened in my default browser. 

Steps: 
1. I add a service to ElectronIM (e.g. hangouts.google.com).
2. I click Login/Sign in in the service - this opens a login webpage in my OS default browser.
3. I log in, but nothing happens. 

I expect this is because the login page is opened in my default browser and not in ElectronIM. Is that correct? Is there anything I can do with this? Thanks in advance for reply. 

I am using Snap version on Ubuntu 19.10.

**Comment by manusa** [comment] 2020-02-11 13:58
Hi @bladimir

Thanks for trying out the application.

Specific OAuth or SSO URLS out of the service URL host must be processed in order to prevent these from being loaded in a separate browser (see https://github.com/manusa/electronim/blob/master/src/tab-manager/redirect.js).

Please, give more details of the specific service you're trying so I can try to reproduce and add an exception.

**Comment by baldimir** [comment] 2020-02-11 14:04
The URLs are:
https://accounts.google.com/signin/v2/
https://auth.redhat.com/auth/

Thanks a lot for help! Btw, I see based on Github profile that you are working for Red Hat. I am also a Red Hatter, so if you need more info, feel free to ping me on Hangouts Chat.

**Comment by baldimir** [comment] 2020-02-11 14:09
The services I am trying are hangouts.google.com and chat.google.com (this chat.google.com goes through Red Hat login)

**Comment by manusa** [comment] 2020-02-11 14:18
Nice to see another Red Hatter around!

I can access chat.google.com, but probably because I logged in prior to adding the "open in browser feature":

![Screenshot from 2020-02-11 15-17-29](https://user-images.githubusercontent.com/488391/74244421-abafd000-4ce1-11ea-94a8-5e9a266f2842.png)

I'll try to fix this one when I get some free time.

**Comment by baldimir** [comment] 2020-02-12 11:17
Thanks a lot, the login works now. Feel free to close this. There is however a separate problem but I will file it as a separate issue as it is related to Google account security.

**Comment by manusa** [comment] 2020-02-12 12:41
I left this one open because with regular Google authentication login is not possible, but this issue is covered in #15. Closing.

**Closed by manusa** 2020-02-12 12:41 UTC
